#!/usr/bin/env python
"""Convert training-schema FR3 handover HDF5 exports into a GR00T-flavored
LeRobot v2.1 dataset (lane A, joint-target actions).

Run it with the GR00T interpreter, which owns h5py / pyarrow / torchcodec:

    ~/Isaac-GR00T/.venv/bin/python harness/data/convert_hdf5_to_gr00t_v2.py \\
        --input '~/runs/franka-sonic/shared/2026-09-03_demos/out/*.hdf5' \\
        --output <run>/out/gr00t_v2 --fps 50 \\
        --task "hand the block from the left arm to the right"

INPUT (written by teleop/recorder.py of franka-bimanual-isaac-sim, video-backed)
------------------------------------------------------------------------------
file attrs: fps, task, source
data/demo_{i}: attrs num_samples=T, images_video_backed=True, [replay_success]
  actions            (T,16) f32  IK-Abs [pos3 quat_wxyz4 grip, pos3 quat_wxyz4 grip]
                                 with grip **+1 = open, -1 = closed**
  obs/joint_pos_left     (T,7)   measured joint positions
  obs/joint_pos_right    (T,7)
  obs/gripper_left       (T,1)   [0,1], 1 = closed
  obs/gripper_right      (T,1)
  obs/joint_target_left  (T,7)   differential-IK joint targets = lane A's labels
  obs/joint_target_right (T,7)
  obs/top | wrist_left | wrist_right
                                 scalar string dataset holding a path RELATIVE
                                 to the HDF5's directory to an h264/yuv420p mp4
                                 at `fps` with exactly T frames. A raw
                                 (T,H,W,3) uint8 array is also accepted and is
                                 encoded here (libx264, yuv420p, crf 20).
  [obs/eef_*, obs/object, initial_cube_pose] are carried only as provenance.

OUTPUT (GR00T-flavored LeRobot v2.1, the layout gr00t/data/dataset/
lerobot_episode_loader.py reads)
------------------------------------------------------------------------------
    <output>/data/chunk-{ep//1000:03d}/episode_{ep:06d}.parquet
    <output>/videos/chunk-{c:03d}/observation.images.{top,wrist_left,wrist_right}/episode_{ep:06d}.mp4
    <output>/meta/{info.json,episodes.jsonl,tasks.jsonl,modality.json,provenance.json}
    <output>/meta/stats.json          (generated by gr00t/data/stats.py unless --no-stats)

16-D vectors, DATASET order (differs from the sim's wire order on purpose;
harness/lane_a/serve_gr00t_joint.py owns the conversion):

    observation.state[t] = [joint_pos_left(7), joint_pos_right(7),
                            gripper_left, gripper_right]
    action[t]            = [joint_target_left(7), joint_target_right(7),
                            grip_l_cmd, grip_r_cmd]

Gripper actions are rescaled from the recorder's +-1 convention to [0,1] with
**1 = closed**, matching the state columns: cmd = (1 - actions[t, 7|15]) / 2.

Refuses to write into a directory that already holds a dataset. Nothing is ever
deleted (AGENTS.md rule o); a stale output directory is an error, not a target.
Prints `CONVERT_DONE: <N> episodes, <F> frames -> <dir>` on success and exits
non-zero on any failure.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import traceback

import h5py
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

sys.path.insert(0, str(Path(__file__).resolve().parent))
import joint_labels  # noqa: E402  (harness/data/joint_labels.py — shared with the A-oracle)

LABEL_MODE = joint_labels.DEFAULT_JOINT_LABEL  # set from --joint-label in convert()
MAX_DELTA_RAD = joint_labels.DEFAULT_MAX_DELTA_RAD


# ----------------------------------------------------------------- constants

CHUNKS_SIZE = 1000
ROBOT_TYPE = "dual_fr3_franka_hand"
CODEBASE_VERSION = "v2.1"
CAMERAS = ("top", "wrist_left", "wrist_right")
DATA_PATH_TMPL = "data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet"
VIDEO_PATH_TMPL = "videos/chunk-{episode_chunk:03d}/{video_key}/episode_{episode_index:06d}.mp4"

# names for the 16-D action / observation.state features, in dataset order
VECTOR_NAMES = (
    [f"left_fr3_joint{i}" for i in range(1, 8)]
    + [f"right_fr3_joint{i}" for i in range(1, 8)]
    + ["left_gripper", "right_gripper"]
)
VECTOR_DIM = len(VECTOR_NAMES)  # 16

# meta/modality.json — the map from the flat 16-D columns to the modality keys
# used by harness/lane_a/modality_config_dual_fr3.py.
STATE_ACTION_SPLIT = {
    "joint_pos_l": {"start": 0, "end": 7},
    "joint_pos_r": {"start": 7, "end": 14},
    "grip": {"start": 14, "end": 16},
}

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MODALITY_CONFIG = REPO_ROOT / "harness" / "lane_a" / "modality_config_dual_fr3.py"
DEFAULT_GR00T_ROOT = Path("~/Isaac-GR00T").expanduser()


class ConvertError(RuntimeError):
    """Anything that makes the produced dataset untrustworthy."""


# ------------------------------------------------------------------- helpers


def log(msg: str) -> None:
    print(msg, flush=True)


def h5_str(value) -> str:
    """Decode an h5py scalar string dataset value (bytes in h5py 3.x)."""
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if isinstance(value, np.ndarray):
        return h5_str(value.item())
    return str(value)


def probe_video(path: Path) -> dict:
    """Return {codec, pix_fmt, width, height, fps} for an mp4, via PyAV."""
    import av

    with av.open(str(path)) as container:
        streams = container.streams.video
        if not streams:
            raise ConvertError(f"no video stream in {path}")
        stream = streams[0]
        ctx = stream.codec_context
        rate = stream.average_rate or ctx.framerate
        return {
            "codec": ctx.name,
            "pix_fmt": str(ctx.pix_fmt),
            "width": int(ctx.width),
            "height": int(ctx.height),
            "fps": float(rate) if rate is not None else None,
        }


def count_frames(path: Path) -> int:
    """Frame count as GR00T's own decoder sees it (torchcodec)."""
    from torchcodec.decoders import VideoDecoder

    return len(VideoDecoder(str(path), device="cpu", dimension_order="NHWC"))


def encode_h264(path: Path, frames: np.ndarray, fps: int) -> None:
    """Encode (T,H,W,3) uint8 RGB to an h264 / yuv420p / crf 20 mp4.

    Mirrors teleop/recorder.py's _encode_video. imageio's FFMPEG plugin is the
    preferred writer (identical settings to the recorder), but imageio_ffmpeg
    is not installed in the GR00T venv on this pod and installing is out of
    scope, so PyAV -- which is installed -- is the fallback. Both produce the
    same codec/pixel format.
    """
    frames = np.asarray(frames)
    if frames.ndim != 4 or frames.shape[-1] != 3 or frames.dtype != np.uint8:
        raise ConvertError(f"expected (T,H,W,3) uint8 frames, got {frames.shape} {frames.dtype}")
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        import imageio.v2 as imageio
        import imageio_ffmpeg  # noqa: F401  (presence check: the plugin needs it)
    except ImportError:
        _encode_h264_pyav(path, frames, fps)
        return
    with imageio.get_writer(
        str(path), format="FFMPEG", mode="I", fps=fps, codec="libx264",
        macro_block_size=1, output_params=["-pix_fmt", "yuv420p", "-crf", "20"],
    ) as writer:
        for frame in frames:
            writer.append_data(np.asarray(frame))


def _encode_h264_pyav(path: Path, frames: np.ndarray, fps: int) -> None:
    import av

    height, width = int(frames.shape[1]), int(frames.shape[2])
    with av.open(str(path), mode="w") as container:
        stream = container.add_stream("libx264", rate=int(fps))
        stream.width = width
        stream.height = height
        stream.pix_fmt = "yuv420p"
        stream.options = {"crf": "20"}
        for frame in frames:
            av_frame = av.VideoFrame.from_ndarray(np.ascontiguousarray(frame), format="rgb24")
            for packet in stream.encode(av_frame):
                container.mux(packet)
        for packet in stream.encode():
            container.mux(packet)


def list_column(values: np.ndarray) -> pa.Array:
    """(T,D) float32 -> arrow list<float32>, one D-vector per row.

    list<float32> (not fixed_size_list) is what LeRobot v2.1 writes and what
    makes ``pd.read_parquet`` hand each cell back as a float32 np.ndarray --
    which lerobot_episode_loader._extract_joint_groups requires
    (``isinstance(df[key].iloc[0], np.ndarray)``).
    """
    values = np.ascontiguousarray(values, dtype=np.float32)
    rows, dim = values.shape
    offsets = pa.array(np.arange(0, rows * dim + 1, dim, dtype=np.int32), type=pa.int32())
    flat = pa.array(values.reshape(-1), type=pa.float32())
    return pa.ListArray.from_arrays(offsets, flat)


# --------------------------------------------------------------- HDF5 -> rows


def read_demo(group: h5py.Group, name: str) -> dict:
    """Pull the arrays lane A needs out of one data/demo_{i} group."""
    if "num_samples" not in group.attrs:
        raise ConvertError(f"{name}: missing attr num_samples")
    length = int(group.attrs["num_samples"])
    if length <= 0:
        raise ConvertError(f"{name}: num_samples={length}")

    obs = group.get("obs")
    if obs is None:
        raise ConvertError(f"{name}: missing obs group")

    def arr(key: str, path: str, width: int) -> np.ndarray:
        node = obs if path == "obs" else group
        if key not in node:
            raise ConvertError(f"{name}: missing {path}/{key}")
        value = np.asarray(node[key][()], dtype=np.float32)
        if value.shape != (length, width):
            raise ConvertError(
                f"{name}: {path}/{key} has shape {value.shape}, expected ({length}, {width})"
            )
        return value

    actions = arr("actions", "demo", 16)
    state = np.concatenate(
        [
            arr("joint_pos_left", "obs", 7),
            arr("joint_pos_right", "obs", 7),
            arr("gripper_left", "obs", 1),
            arr("gripper_right", "obs", 1),
        ],
        axis=1,
    )
    # grip command: recorder +1 = open / -1 = closed  ->  dataset 1 = closed
    grip_cmd = (1.0 - actions[:, [7, 15]]) / 2.0
    # arm label: see harness/data/joint_labels.py (decision + measurements); LABEL_MODE is set
    # from --joint-label in convert() so the oracle replay and the dataset agree by construction.
    action = np.concatenate(
        [
            joint_labels.arm_label(arr("joint_pos_left", "obs", 7), arr("joint_target_left", "obs", 7),
                                   LABEL_MODE, MAX_DELTA_RAD),
            joint_labels.arm_label(arr("joint_pos_right", "obs", 7), arr("joint_target_right", "obs", 7),
                                   LABEL_MODE, MAX_DELTA_RAD),
            grip_cmd,
        ],
        axis=1,
    ).astype(np.float32)

    if state.shape != (length, VECTOR_DIM) or action.shape != (length, VECTOR_DIM):
        raise ConvertError(f"{name}: built vectors {state.shape}/{action.shape} != ({length}, 16)")
    for label, value in (("observation.state", state), ("action", action)):
        if not np.isfinite(value).all():
            raise ConvertError(f"{name}: {label} contains non-finite values")

    videos: dict[str, object] = {}
    for camera in CAMERAS:
        if camera not in obs:
            raise ConvertError(f"{name}: missing obs/{camera}")
        node = obs[camera]
        if node.shape == () or node.dtype.kind in ("O", "S", "U"):
            videos[camera] = h5_str(node[()])  # relative path to an mp4
        else:
            videos[camera] = np.asarray(node[()])  # raw (T,H,W,3) uint8

    replay_success = group.attrs.get("replay_success", None)
    if replay_success is not None:
        replay_success = bool(replay_success)

    return {
        "length": length,
        "state": state,
        "action": action,
        "videos": videos,
        "replay_success": replay_success,
        "video_backed": bool(group.attrs.get("images_video_backed", False)),
    }


def collect_demos(paths: list[Path], skip_failed: bool, max_episodes: int) -> list[dict]:
    """Walk every input file in order and return the demos to convert."""
    selected: list[dict] = []
    for path in paths:
        with h5py.File(path, "r") as handle:
            file_fps = handle.attrs.get("fps", None)
            file_task = handle.attrs.get("task", None)
            if "data" not in handle:
                raise ConvertError(f"{path}: no /data group")
            names = sorted(
                (n for n in handle["data"] if n.startswith("demo_")),
                key=lambda n: int(n.split("_")[1]),
            )
            if not names:
                raise ConvertError(f"{path}: /data holds no demo_* groups")
            for name in names:
                if max_episodes and len(selected) >= max_episodes:
                    return selected
                group = handle["data"][name]
                success = group.attrs.get("replay_success", None)
                if skip_failed and success is not None and not bool(success):
                    log(f"  skip {path.name}:{name} (replay_success=False)")
                    continue
                demo = read_demo(group, f"{path.name}:{name}")
                demo["source_file"] = str(path)
                demo["source_dir"] = str(path.parent)
                demo["demo_name"] = name
                demo["file_fps"] = None if file_fps is None else float(file_fps)
                demo["file_task"] = None if file_task is None else h5_str(file_task)
                selected.append(demo)
    return selected


# ----------------------------------------------------------------- meta files


def build_info(fps: int, episodes: list[dict], video_meta: dict[str, dict]) -> dict:
    total_frames = int(sum(e["length"] for e in episodes))
    total_episodes = len(episodes)
    features: dict = {}
    for key in ("action", "observation.state"):
        features[key] = {
            "dtype": "float32",
            "shape": [VECTOR_DIM],
            "names": list(VECTOR_NAMES),
        }
    for camera in CAMERAS:
        meta = video_meta[camera]
        height, width = meta["height"], meta["width"]
        features[f"observation.images.{camera}"] = {
            "dtype": "video",
            "shape": [height, width, 3],
            "names": ["height", "width", "channels"],
            "info": {
                "video.height": height,
                "video.width": width,
                "video.codec": "h264",
                "video.pix_fmt": "yuv420p",
                "video.is_depth_map": False,
                "video.fps": fps,
                "video.channels": 3,
                "has_audio": False,
            },
        }
    features["timestamp"] = {"dtype": "float32", "shape": [1], "names": None}
    for key in ("frame_index", "episode_index", "index", "task_index"):
        features[key] = {"dtype": "int64", "shape": [1], "names": None}

    total_chunks = ((total_episodes - 1) // CHUNKS_SIZE + 1) if total_episodes else 0
    return {
        "codebase_version": CODEBASE_VERSION,
        "robot_type": ROBOT_TYPE,
        "total_episodes": total_episodes,
        "total_frames": total_frames,
        "total_tasks": 1,
        "chunks_size": CHUNKS_SIZE,
        "fps": fps,
        "splits": {"train": f"0:{total_episodes}"},
        "data_path": DATA_PATH_TMPL,
        "video_path": VIDEO_PATH_TMPL,
        "features": features,
        "total_chunks": total_chunks,
        "total_videos": total_episodes * len(CAMERAS),
    }


def build_modality() -> dict:
    return {
        "state": {k: dict(v) for k, v in STATE_ACTION_SPLIT.items()},
        "action": {k: dict(v) for k, v in STATE_ACTION_SPLIT.items()},
        "video": {c: {"original_key": f"observation.images.{c}"} for c in CAMERAS},
        "annotation": {"human.task_description": {"original_key": "task_index"}},
    }


def write_jsonl(path: Path, rows: list[dict]) -> None:
    with open(path, "w") as handle:
        for row in rows:
            handle.write(json.dumps(row) + "\n")


# --------------------------------------------------------------------- stages


def resolve_inputs(patterns: list[str]) -> list[Path]:
    paths: list[Path] = []
    for pattern in patterns:
        expanded = os.path.expanduser(pattern)
        hits = sorted(glob.glob(expanded))
        if not hits:
            candidate = Path(expanded)
            if candidate.is_file():
                hits = [str(candidate)]
        if not hits:
            raise ConvertError(f"--input matched nothing: {pattern}")
        for hit in hits:
            resolved = Path(hit).resolve()
            if resolved not in paths:
                paths.append(resolved)
    return paths


def guard_output(output: Path) -> None:
    """Refuse to write on top of an existing dataset (never delete, rule o)."""
    if not output.exists():
        return
    if not output.is_dir():
        raise ConvertError(f"--output exists and is not a directory: {output}")
    existing = [
        p
        for p in (output / "meta" / "info.json", output / "meta" / "modality.json")
        if p.exists()
    ] + sorted(output.glob("data/chunk-*/episode_*.parquet"))[:1]
    if existing:
        raise ConvertError(
            f"--output already contains a dataset ({existing[0]}). "
            "Refusing to overwrite; nothing on this pod is ever deleted "
            "(AGENTS.md rule o) -- pick a fresh --output directory."
        )


VIDEO_SIZE: tuple[int, int] | None = None  # (W, H) every mp4 must have; set from --video-size


def parse_size(text: str | None) -> tuple[int, int] | None:
    if not text:
        return None
    w, h = text.lower().split("x")
    return int(w), int(h)


def transcode_to_size(src: Path, dest: Path, size: tuple[int, int]) -> None:
    """Rescale an mp4 to WxH with ffmpeg (area filter, h264/yuv420p/crf 20), frame count kept.

    GR00T stacks all camera views into ONE tensor after its shortest-edge resize, so every view
    must resize to the same shape — a 640x360 top and 424x240 wrists become 455x256 vs 452x256
    and `torch.stack` fails in the first batch (lane_a finetune attempt 3, 2026-09-03).
    """
    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        raise ConvertError("ffmpeg not found on PATH; needed to rescale videos to --video-size")
    dest.parent.mkdir(parents=True, exist_ok=True)
    cmd = [ffmpeg, "-hide_banner", "-loglevel", "error", "-y", "-i", str(src),
           "-vf", f"scale={size[0]}:{size[1]}:flags=area", "-vsync", "passthrough",
           "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20", "-movflags", "+faststart", str(dest)]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    if result.returncode != 0:
        raise ConvertError(f"ffmpeg failed rescaling {src} -> {dest}: {result.stderr.strip()[:400]}")


def place_video(demo: dict, camera: str, dest: Path, fps: int, length: int) -> dict:
    """Copy (or encode / rescale) one camera's mp4 into the dataset and verify it."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    source = demo["videos"][camera]
    if isinstance(source, str):
        src_path = Path(demo["source_dir"]) / source
        if not src_path.is_file():
            raise ConvertError(f"{demo['demo_name']}: obs/{camera} points at a missing file {src_path}")
        probe = probe_video(src_path)
        size_ok = VIDEO_SIZE is None or (probe["width"], probe["height"]) == VIDEO_SIZE
        if probe["codec"] == "h264" and probe["pix_fmt"] == "yuv420p" and size_ok:
            shutil.copy2(src_path, dest)  # already the target codec and size: no transcode
        elif not size_ok:
            log(f"    rescaling {camera} {probe['width']}x{probe['height']} -> {VIDEO_SIZE[0]}x{VIDEO_SIZE[1]}")
            transcode_to_size(src_path, dest, VIDEO_SIZE)
        else:
            log(
                f"    transcoding {camera} ({probe['codec']}/{probe['pix_fmt']} "
                f"-> h264/yuv420p)"
            )
            from torchcodec.decoders import VideoDecoder

            decoder = VideoDecoder(str(src_path), device="cpu", dimension_order="NHWC")
            frames = decoder.get_frames_at(indices=list(range(len(decoder)))).data.numpy()
            encode_h264(dest, frames, fps)
    else:
        if VIDEO_SIZE is not None and (source.shape[2], source.shape[1]) != VIDEO_SIZE:
            import cv2

            source = np.stack([cv2.resize(f, VIDEO_SIZE, interpolation=cv2.INTER_AREA) for f in source])
        encode_h264(dest, source, fps)

    probe = probe_video(dest)
    if probe["codec"] != "h264" or probe["pix_fmt"] != "yuv420p":
        raise ConvertError(f"{dest}: expected h264/yuv420p, got {probe['codec']}/{probe['pix_fmt']}")
    if VIDEO_SIZE is not None and (probe["width"], probe["height"]) != VIDEO_SIZE:
        raise ConvertError(f"{dest}: is {probe['width']}x{probe['height']}, expected {VIDEO_SIZE}")
    frames = count_frames(dest)
    if frames != length:
        raise ConvertError(
            f"{dest}: has {frames} frames but the episode has {length} samples"
        )
    return probe


def write_episode(
    output: Path, ep_index: int, demo: dict, fps: int, index_offset: int
) -> dict[str, dict]:
    """Write one episode's parquet + three mp4s. Returns per-camera video meta."""
    length = demo["length"]
    chunk = ep_index // CHUNKS_SIZE
    parquet_path = output / DATA_PATH_TMPL.format(episode_chunk=chunk, episode_index=ep_index)
    parquet_path.parent.mkdir(parents=True, exist_ok=True)

    table = pa.table(
        {
            "observation.state": list_column(demo["state"]),
            "action": list_column(demo["action"]),
            "timestamp": pa.array(
                (np.arange(length, dtype=np.float32) / np.float32(fps)), type=pa.float32()
            ),
            "frame_index": pa.array(np.arange(length, dtype=np.int64), type=pa.int64()),
            "episode_index": pa.array(
                np.full(length, ep_index, dtype=np.int64), type=pa.int64()
            ),
            "index": pa.array(
                np.arange(index_offset, index_offset + length, dtype=np.int64), type=pa.int64()
            ),
            "task_index": pa.array(np.zeros(length, dtype=np.int64), type=pa.int64()),
        }
    )
    pq.write_table(table, parquet_path)

    video_meta = {}
    for camera in CAMERAS:
        dest = output / VIDEO_PATH_TMPL.format(
            episode_chunk=chunk,
            video_key=f"observation.images.{camera}",
            episode_index=ep_index,
        )
        video_meta[camera] = place_video(demo, camera, dest, fps, length)
    return video_meta


def run_stats(output: Path, gr00t_root: Path, modality_config: Path) -> None:
    interpreter = gr00t_root / ".venv" / "bin" / "python"
    if not interpreter.is_file():
        interpreter = Path(sys.executable)
    cmd = [
        str(interpreter),
        "gr00t/data/stats.py",
        "--dataset-path",
        str(output),
        "--embodiment-tag",
        "NEW_EMBODIMENT",
        "--modality-config-path",
        str(modality_config),
    ]
    log(f"[stats] {' '.join(cmd)}  (cwd={gr00t_root})")
    result = subprocess.run(cmd, cwd=str(gr00t_root))
    if result.returncode != 0:
        raise ConvertError(f"gr00t/data/stats.py failed with rc={result.returncode}")
    if not (output / "meta" / "stats.json").is_file():
        raise ConvertError("gr00t/data/stats.py did not produce meta/stats.json")


def run_validation(output: Path, modality_config: Path, max_episodes: int) -> None:
    """Load the dataset back through GR00T's own loader."""
    import importlib

    sys.path.insert(0, str(modality_config.parent))
    importlib.import_module(modality_config.stem)
    from gr00t.configs.data.embodiment_configs import MODALITY_CONFIGS
    from gr00t.data.dataset.lerobot_episode_loader import LeRobotEpisodeLoader

    configs = MODALITY_CONFIGS["new_embodiment"]
    loader = LeRobotEpisodeLoader(str(output), configs)
    log(f"[validate] LeRobotEpisodeLoader: {len(loader)} episodes, fps={loader.fps}")

    stats = loader.get_dataset_statistics()
    for modality in ("state", "action"):
        for key in configs[modality].modality_keys:
            mean = stats[modality][key]["mean"]
            log(f"[validate] stats {modality}.{key}: dim={len(mean)}")

    count = len(loader) if not max_episodes else min(len(loader), max_episodes)
    for idx in range(count):
        frame = loader[idx]
        pieces = []
        for column in frame.columns:
            first = frame[column].iloc[0]
            shape = getattr(first, "shape", None)
            pieces.append(f"{column}{list(shape) if shape is not None else '=' + str(type(first).__name__)}")
        log(f"[validate] episode {idx}: rows={len(frame)} " + " ".join(pieces))
        for key in configs["video"].modality_keys:
            first = frame[f"video.{key}"].iloc[0]
            arr = np.asarray(first)
            if arr.ndim != 3 or arr.shape[-1] != 3:
                raise ConvertError(f"episode {idx}: video.{key} frame 0 has shape {arr.shape}")
            log(f"[validate]   video.{key} frame0 {arr.shape} {arr.dtype}")


# ----------------------------------------------------------------------- main


def convert(args: argparse.Namespace) -> int:
    global LABEL_MODE, MAX_DELTA_RAD, VIDEO_SIZE
    LABEL_MODE, MAX_DELTA_RAD = args.joint_label, args.max_delta_rad
    VIDEO_SIZE = parse_size(args.video_size)
    log(f"[label] arm action = {joint_labels.describe(LABEL_MODE, MAX_DELTA_RAD)}")
    log(f"[video] single resolution for all cameras: {VIDEO_SIZE or 'as exported (no rescale)'}")
    output = Path(os.path.expanduser(args.output)).resolve()
    modality_config = Path(os.path.expanduser(args.modality_config_path)).resolve()
    gr00t_root = Path(os.path.expanduser(args.gr00t_root)).resolve()
    if not modality_config.is_file():
        raise ConvertError(f"--modality-config-path does not exist: {modality_config}")

    inputs = resolve_inputs(args.input)
    log(f"[input] {len(inputs)} HDF5 file(s):")
    for path in inputs:
        log(f"  {path}")
    guard_output(output)

    demos = collect_demos(inputs, args.skip_failed_replays, args.max_episodes)
    if not demos:
        raise ConvertError("no episodes selected (all skipped?)")
    for demo in demos:
        if demo["file_fps"] is not None and abs(demo["file_fps"] - args.fps) > 1e-6:
            log(
                f"WARNING: {demo['source_file']} was recorded at fps={demo['file_fps']} "
                f"but --fps {args.fps} was requested; using {args.fps} for timestamps."
            )
    log(f"[select] {len(demos)} episode(s), {sum(d['length'] for d in demos)} frames")

    (output / "meta").mkdir(parents=True, exist_ok=True)

    episodes_meta: list[dict] = []
    provenance: dict[str, dict] = {}
    video_meta: dict[str, dict] = {}
    index_offset = 0
    for ep_index, demo in enumerate(demos):
        log(f"[episode {ep_index}] {demo['source_file']}:{demo['demo_name']} T={demo['length']}")
        per_camera = write_episode(output, ep_index, demo, args.fps, index_offset)
        for camera, probe in per_camera.items():
            if camera not in video_meta:
                video_meta[camera] = probe
            elif (probe["height"], probe["width"]) != (
                video_meta[camera]["height"],
                video_meta[camera]["width"],
            ):
                raise ConvertError(
                    f"episode {ep_index}: camera {camera} is "
                    f"{probe['width']}x{probe['height']} but earlier episodes are "
                    f"{video_meta[camera]['width']}x{video_meta[camera]['height']}; "
                    "one resolution per camera is required by meta/info.json"
                )
        index_offset += demo["length"]
        episodes_meta.append(
            {"episode_index": ep_index, "tasks": [args.task], "length": demo["length"]}
        )
        provenance[str(ep_index)] = {
            "source_file": demo["source_file"],
            "demo_name": demo["demo_name"],
            "length": demo["length"],
            "replay_success": demo["replay_success"],
        }

    info = build_info(args.fps, demos, video_meta)
    with open(output / "meta" / "info.json", "w") as handle:
        json.dump(info, handle, indent=4)
    write_jsonl(output / "meta" / "episodes.jsonl", episodes_meta)
    write_jsonl(output / "meta" / "tasks.jsonl", [{"task_index": 0, "task": args.task}])
    with open(output / "meta" / "modality.json", "w") as handle:
        json.dump(build_modality(), handle, indent=4)
    provenance["joint_label"] = {"mode": LABEL_MODE, "max_delta_rad": MAX_DELTA_RAD,
                                 "description": joint_labels.describe(LABEL_MODE, MAX_DELTA_RAD)}
    provenance["video_size"] = list(VIDEO_SIZE) if VIDEO_SIZE else None
    with open(output / "meta" / "provenance.json", "w") as handle:
        json.dump(provenance, handle, indent=4)
    log(f"[meta] wrote info.json, episodes.jsonl, tasks.jsonl, modality.json, provenance.json")

    if args.stats:
        run_stats(output, gr00t_root, modality_config)
    else:
        log("[stats] skipped (--no-stats)")

    if args.validate:
        run_validation(output, modality_config, args.validate_max_episodes)
    else:
        log("[validate] skipped (--no-validate)")

    log(
        f"CONVERT_DONE: {info['total_episodes']} episodes, "
        f"{info['total_frames']} frames -> {output}"
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--input", nargs="+", required=True,
        help="one or more HDF5 paths or globs (quote globs so the shell keeps them)",
    )
    parser.add_argument("--output", required=True, help="dataset root to create")
    parser.add_argument("--fps", type=int, default=50)
    parser.add_argument(
        "--task", default="hand the block from the left arm to the right",
        help="the single task string; also the language annotation",
    )
    parser.add_argument(
        "--max-episodes", type=int, default=0, help="0 = every episode found"
    )
    parser.add_argument(
        "--skip-failed-replays", dest="skip_failed_replays",
        action="store_true", default=True,
        help="drop demos with replay_success=False (default)",
    )
    parser.add_argument(
        "--no-skip-failed-replays", dest="skip_failed_replays", action="store_false"
    )
    parser.add_argument(
        "--joint-label", choices=joint_labels.JOINT_LABELS, default=joint_labels.DEFAULT_JOINT_LABEL,
        help="arm action label (harness/data/joint_labels.py); the A-oracle must replay the same one",
    )
    parser.add_argument("--max-delta-rad", type=float, default=joint_labels.DEFAULT_MAX_DELTA_RAD,
                        help="per-step move bound for --joint-label ik_target_delta")
    parser.add_argument("--video-size", default="640x360",
                        help="WxH every camera video must have (GR00T stacks the views: one resolution); "
                             "mismatching mp4s are rescaled with ffmpeg. '' = keep as exported")
    parser.add_argument("--modality-config-path", default=str(DEFAULT_MODALITY_CONFIG))
    parser.add_argument("--stats", dest="stats", action="store_true", default=True)
    parser.add_argument("--no-stats", dest="stats", action="store_false")
    parser.add_argument("--validate", dest="validate", action="store_true", default=True)
    parser.add_argument("--no-validate", dest="validate", action="store_false")
    parser.add_argument(
        "--validate-max-episodes", type=int, default=0,
        help="0 = validate every episode; the loader decodes a whole episode "
             "per call, so cap this on large datasets",
    )
    parser.add_argument(
        "--gr00t-root", default=str(DEFAULT_GR00T_ROOT),
        help="Isaac-GR00T checkout; its .venv python runs gr00t/data/stats.py",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return convert(args)
    except Exception as exc:  # noqa: BLE001 - one exit path, always non-zero
        traceback.print_exc()
        print(f"CONVERT_FAILED: {type(exc).__name__}: {exc}", flush=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())
